export const CLEAR_STORE_REQUEST = "CLEAR_STORE_REQUEST";

// Patients

export const GET_ALL_PATIENTS = "GET_ALL_PATIENTS";
export const GET_ALL_PATIENT_IDS_SUCCESS = "GET_ALL_PATIENT_IDS_SUCCESS";
export const GET_ALL_PATIENT_IDS_ERROR = "GET_ALL_PATIENT_IDS_ERROR";

export const GET_PATIENT_WITH_ID = "GET_PATIENT_WITH_ID";
export const GET_PATIENT_WITH_ID_SUCCESS = "GET_PATIENT_WITH_ID_SUCCESS";
export const GET_PATIENT_WITH_ID_ERROR = "GET_PATIENT_WITH_ID_ERROR";

// Study

export const GET_STUDY_WITH_ID_SUCCESS = "GET_STUDY_WITH_ID_SUCCESS";
export const GET_STUDY_WITH_ID_ERROR = "GET_STUDY_WITH_ID_ERROR";

export const SELECT_STUDY = "SELECT_STUDY";